{
  "skip": "https://github.com/open-telemetry/opentelemetry-ebpf-profiler/issues/416",
  "coredump-ref": "4652115623df00987a1a480431a360edbd67b0795e9529543d40be190e37c74d",
  "threads": [
    {
      "lwp": 10,
      "frames": [
        "libpython3.12.so.1.0+0x19b80d",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "fib+3 in //mnt/trash/qwe.py:4",
        "<module>+6 in //mnt/trash/qwe.py:7",
        "<interpreter trampoline>+0 in <shim>:1",
        "libpython3.12.so.1.0+0x91617",
        "libpython3.12.so.1.0+0x1ecfe2",
        "libpython3.12.so.1.0+0x2136b6",
        "libpython3.12.so.1.0+0x20c91b",
        "libpython3.12.so.1.0+0x226f72",
        "libpython3.12.so.1.0+0x2264f1",
        "libpython3.12.so.1.0+0x2260d3",
        "libpython3.12.so.1.0+0x21f742",
        "libpython3.12.so.1.0+0x1d6ed6",
        "ld-musl-x86_64.so.1+0x1c709",
        "python3.12+0x1045",
        "<unwinding aborted due to error native_small_pc>"
      ]
    }
  ],
  "modules": [
    {
      "ref": "a621ea443bba20ffbdb5322633c5a1bf439905baa5822973b2cafc4106c64789",
      "local-path": "/usr/lib/libpython3.12.so.1.0"
    },
    {
      "ref": "9ef79f767e2c2cfde043a023acb0021f6261f560b27035c961d282cecc026db9",
      "local-path": "/usr/lib/debug/usr/lib/libpython3.12.so.1.0.debug"
    },
    {
      "ref": "c9cbfe6a266c104f74629a257e2017020cba7a0da97caefa4c1d068ea6fe698c",
      "local-path": "/lib/ld-musl-x86_64.so.1"
    },
    {
      "ref": "983f4cac5caf833fbf7d5d28ac8d6a55d3cbab6152d37a246af1a9991f72d8b1",
      "local-path": "/usr/lib/debug/lib/ld-musl-x86_64.so.1.debug"
    },
    {
      "ref": "9cf22fb673cad95247584fd0bc21b95aa37ae152a8bd01022a494e4f7ec3854c",
      "local-path": "/usr/bin/python3.12"
    },
    {
      "ref": "f2c83c6e5aea0e1e42b69e344a2eb0aac35b361cad7497157f727dbe30b8565e",
      "local-path": "/usr/lib/debug/usr/bin/python3.12.debug"
    }
  ]
}
